#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Dune 2000
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🪱
# @raycast.packageName Games

open -a "OpenRA - Dune 2000"
