#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title Fallout 1
# @raycast.mode silent
# @raycast.icon 🎮
# @raycast.packageName Games

cd ~/Games/Fallout1 && exec ./Fallout\ Community\ Edition.app/Contents/MacOS/fallout-ce
