#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Red Alert
# @raycast.mode silent

# Optional parameters:
# @raycast.icon ⚔️
# @raycast.packageName Games

open -a "OpenRA - Red Alert"
