#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Zelda: Ocarina of Time
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🗡️
# @raycast.packageName Games

open -a "soh"
